config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  get 'home/index'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments, only: [:new, :create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 4000 }

  def subject
    title
  end

  def last_comment
    comments.last
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :body, presence: true, length: { maximum: 4000 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create

    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path
    else
      render action: 'new', status: :unprocessable_entity
    end

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end

  end

  def destroy
    @article = Article.find params[:id]
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create

    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end

  end

  private
  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
    <% article.errors.full_messages_for(:title).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :text, class:"form-label" %>
    <%= form.text_area :text, class:"form-control", rows:"5" %>
    <% article.errors.full_messages_for(:text).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>

  <%= form.button class:"btn btn-primary", value: "Send article" %>

<% end %>

app/views/articles/create.html.erb
<p>Thank you. Your article is posted</p>

app/views/articles/edit.html.erb
<h1><%= t("articles.edit_article") %></h1>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h3><%= t("articles.articles") %></h3>

<% @articles.each do |article| %>

  <h3><%= link_to article.title, article %></h3>

  <p> <%= article.text %></p>

<% end %>
<br />
<hr />

app/views/articles/new.html.erb
<h1><%= t("articles.new_article") %></h1>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.text %></p>

<% if user_signed_in? %>

  <div class="d-grid gap-2 d-md-flex justify-content-md-end">

    <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-success btn-sm", value: "Edit" %>

    <%= link_to "Destroy", article_path(@article), class:"btn btn-outline-danger btn-sm", data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }, value: "Destroy" %>

  </div>

<% end %>

<% if user_signed_in? %>
<h4><%= t("comments.add_comment") %></h4>
  <%= render 'comments/form' %>
<br />
<hr />
<% end %>
<h4><%= t("comments.comments") %></h4>
<hr />
<%= render @article.comments %>

app/views/comments/_comment.html.erb
<h4><%= comment.author %></h4>
<p><%= comment.body %></p>
<p><%= comment.created_at %></p>
<hr />

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

  <%= form.text_field :author, type: 'hidden', value: current_user.username %>

  <div class="mb-3">
    <%= form.text_area :body, class:"form-control", rows:"3" %>
  </div>

  <%= form.button class:"btn btn-primary", value: "Create Comment" %>

<% end %>

app/views/contacts/create.html.erb
<p>Thank you!</p>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact && @contact.errors.any? %>
        <% @contact.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
        <% end %>
  <% end %>

  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    <div id="emailHelp" class="form-text">
      We'll never share your email with anyone else.
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :message, class:"form-label" %>
    <%= f.text_area :message, class:"form-control", rows:"5" %>
  </div>


  <%= f.button class:"btn btn-primary", value: "Send message" %>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
      <title>Blog</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg bg-light">

        <div class="container-fluid">
          <%= link_to 'myBLOG', home_index_path, class: "navbar-brand" %>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'Articles', articles_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Contact us', contacts_path, class: "nav-link" %>
              </li>
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'New', new_article_path, class: "nav-link" %>
              </li>
              <% end %>
            </ul>

            <div class="d-flex">

              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if user_signed_in? %>

                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Hello, <%= current_user.username %>
                    </button>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
                      </li>
                    </ul>
                  </div>

                <% else %>
                  <li class="nav-item">
                    <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
                  </li>

                  <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
                  </li>
                <% end %>
              </ul>

            </div>
          </div>
        </div>
      </nav>

      <!-- <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->

        <%= yield %>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/pages/terms.html.erb
<h1>Terms and Services</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>